### ISSUE TITLE
install.sh 找不到

### ISSUE THREAD

**Issue by Begginm** [BolunHan/miui.eu.localization#2]
前面按照教程把 "Mipay", "NextPay", "TSMClient" 和 "UPTsmService" 的文件夹都复制出来了，所有ota也都删除了，只有UPTsmService有lib文件夹，里面的文件还没有对应的。但是我没找到install.sh应该在哪里找，clone下来的magisk-module-template-master.zip也只有后面步骤的system.prop。还有最后的打包我没看懂要咋操作。我下载的卡刷包版本是V14.0.4.0.TJBCNXM。手机为xiaomi10，代号为umi。希望大佬解答

**Comment by BolunHan** [comment]
install.sh 就是代码库中的那个脚本哦！

https://github.com/BolunHan/miui.eu.localization/blob/main/install.sh
